# Aplikasi 1
<VirtualHost *:80>
    ServerName nama-aplikasi1.com
    ServerAlias www.nama-aplikasi1.com
    DocumentRoot /var/www/nama-aplikasi1/public
    <Directory /var/www/nama-aplikasi1/public>
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/nama-aplikasi1-error.log
    CustomLog ${APACHE_LOG_DIR}/nama-aplikasi1-access.log combined
</VirtualHost>

# Aplikasi 2
<VirtualHost *:80>
    ServerName nama-aplikasi2.com
    ServerAlias www.nama-aplikasi2.com
    DocumentRoot /var/www/nama-aplikasi2/public
    <Directory /var/www/nama-aplikasi2/public>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>